-- =====================================================================
--  Seed Sri Lanka cities (Province → District → Town)
--
--  Matches exactly the towns in the frontend src/data/cities.ts so that
--  the city name selected in Place Order can be resolved to a city_id
--  and saved on the customers table.  Without this seed the cities table
--  is empty, every customer has city_id = NULL, and the Reports page
--  shows "Unspecified" for all cities.
-- =====================================================================

INSERT INTO cities (province, district, name, is_active) VALUES
  -- Western – Colombo
  ('Western','Colombo','Colombo',TRUE),
  ('Western','Colombo','Dehiwala',TRUE),
  ('Western','Colombo','Moratuwa',TRUE),
  ('Western','Colombo','Sri Jayawardenepura Kotte',TRUE),
  ('Western','Colombo','Kaduwela',TRUE),
  ('Western','Colombo','Maharagama',TRUE),
  ('Western','Colombo','Nugegoda',TRUE),
  ('Western','Colombo','Piliyandala',TRUE),
  ('Western','Colombo','Avissawella',TRUE),
  ('Western','Colombo','Hanwella',TRUE),
  ('Western','Colombo','Boralesgamuwa',TRUE),
  ('Western','Colombo','Homagama',TRUE),
  ('Western','Colombo','Kesbewa',TRUE),
  ('Western','Colombo','Kolonnawa',TRUE),
  ('Western','Colombo','Kotikawatte (Mulleriyawa)',TRUE),
  ('Western','Colombo','Seethawaka',TRUE),
  ('Western','Colombo','Seethawakapura',TRUE),
  -- Western – Gampaha
  ('Western','Gampaha','Negombo',TRUE),
  ('Western','Gampaha','Gampaha',TRUE),
  ('Western','Gampaha','Ja-Ela',TRUE),
  ('Western','Gampaha','Katunayake',TRUE),
  ('Western','Gampaha','Wattala',TRUE),
  ('Western','Gampaha','Ragama',TRUE),
  ('Western','Gampaha','Minuwangoda',TRUE),
  ('Western','Gampaha','Divulapitiya',TRUE),
  ('Western','Gampaha','Mirigama',TRUE),
  ('Western','Gampaha','Nittambuwa',TRUE),
  ('Western','Gampaha','Veyangoda',TRUE),
  ('Western','Gampaha','Kiribathgoda',TRUE),
  ('Western','Gampaha','Kelaniya',TRUE),
  ('Western','Gampaha','Peliyagoda',TRUE),
  ('Western','Gampaha','Kadawatha',TRUE),
  ('Western','Gampaha','Biyagama',TRUE),
  ('Western','Gampaha','Attanagalle',TRUE),
  ('Western','Gampaha','Dompe',TRUE),
  ('Western','Gampaha','Katana',TRUE),
  ('Western','Gampaha','Mahara',TRUE),
  -- Western – Kalutara
  ('Western','Kalutara','Kalutara',TRUE),
  ('Western','Kalutara','Panadura',TRUE),
  ('Western','Kalutara','Horana',TRUE),
  ('Western','Kalutara','Matugama',TRUE),
  ('Western','Kalutara','Bandaragama',TRUE),
  ('Western','Kalutara','Ingiriya',TRUE),
  ('Western','Kalutara','Agalawatta',TRUE),
  ('Western','Kalutara','Aluthgama',TRUE),
  ('Western','Kalutara','Bentota',TRUE),
  ('Western','Kalutara','Beruwala',TRUE),
  ('Western','Kalutara','Paiyagala',TRUE),
  ('Western','Kalutara','Wadduwa',TRUE),
  ('Western','Kalutara','Bulathsinhala',TRUE),
  ('Western','Kalutara','Dodangoda',TRUE),
  ('Western','Kalutara','Madurawala',TRUE),
  ('Western','Kalutara','Millaniya',TRUE),
  ('Western','Kalutara','Palindanuwara',TRUE),
  ('Western','Kalutara','Walallawita',TRUE),
  -- Central – Kandy
  ('Central','Kandy','Kandy',TRUE),
  ('Central','Kandy','Gampola',TRUE),
  ('Central','Kandy','Nawalapitiya',TRUE),
  ('Central','Kandy','Akurana',TRUE),
  ('Central','Kandy','Wattegama',TRUE),
  ('Central','Kandy','Kadugannawa',TRUE),
  -- Central – Matale
  ('Central','Matale','Matale',TRUE),
  ('Central','Matale','Dambulla',TRUE),
  ('Central','Matale','Sigiriya',TRUE),
  -- Central – Nuwara Eliya
  ('Central','Nuwara Eliya','Nuwara Eliya',TRUE),
  ('Central','Nuwara Eliya','Hatton',TRUE),
  ('Central','Nuwara Eliya','Talawakele-Lindula',TRUE),
  ('Central','Nuwara Eliya','Maskeliya',TRUE),
  ('Central','Nuwara Eliya','Ginigathhena',TRUE),
  ('Central','Nuwara Eliya','Kotagala',TRUE),
  ('Central','Nuwara Eliya','Walapane',TRUE),
  -- Southern – Galle
  ('Southern','Galle','Galle',TRUE),
  ('Southern','Galle','Ambalangoda',TRUE),
  ('Southern','Galle','Hikkaduwa',TRUE),
  ('Southern','Galle','Elpitiya',TRUE),
  ('Southern','Galle','Baddegama',TRUE),
  ('Southern','Galle','Karandeniya',TRUE),
  -- Southern – Matara
  ('Southern','Matara','Matara',TRUE),
  ('Southern','Matara','Akuressa',TRUE),
  ('Southern','Matara','Deniyaya',TRUE),
  ('Southern','Matara','Dickwella',TRUE),
  ('Southern','Matara','Weligama',TRUE),
  ('Southern','Matara','Mirissa',TRUE),
  ('Southern','Matara','Kamburupitiya',TRUE),
  ('Southern','Matara','Devinuwara',TRUE),
  ('Southern','Matara','Hakmana',TRUE),
  -- Southern – Hambantota
  ('Southern','Hambantota','Hambantota',TRUE),
  ('Southern','Hambantota','Tangalle',TRUE),
  ('Southern','Hambantota','Tissamaharama',TRUE),
  ('Southern','Hambantota','Weeraketiya',TRUE),
  -- Northern – Jaffna
  ('Northern','Jaffna','Jaffna',TRUE),
  ('Northern','Jaffna','Point Pedro',TRUE),
  ('Northern','Jaffna','Chavakachcheri',TRUE),
  ('Northern','Jaffna','Valvettithurai',TRUE),
  ('Northern','Kilinochchi','Kilinochchi',TRUE),
  ('Northern','Mannar','Mannar',TRUE),
  ('Northern','Vavuniya','Vavuniya',TRUE),
  ('Northern','Mullaitivu','Mullaitivu',TRUE),
  -- Eastern – Batticaloa
  ('Eastern','Batticaloa','Batticaloa',TRUE),
  ('Eastern','Batticaloa','Kattankudy',TRUE),
  ('Eastern','Batticaloa','Eravur',TRUE),
  -- Eastern – Ampara
  ('Eastern','Ampara','Ampara',TRUE),
  ('Eastern','Ampara','Akkaraipattu',TRUE),
  ('Eastern','Ampara','Kalmunai',TRUE),
  ('Eastern','Ampara','Dehiattakandiya',TRUE),
  ('Eastern','Ampara','Pottuvil',TRUE),
  -- Eastern – Trincomalee
  ('Eastern','Trincomalee','Trincomalee',TRUE),
  ('Eastern','Trincomalee','Muttur',TRUE),
  ('Eastern','Trincomalee','Kantale',TRUE),
  ('Eastern','Trincomalee','Kinniya',TRUE),
  -- North Western – Kurunegala
  ('North Western','Kurunegala','Kurunegala',TRUE),
  ('North Western','Kurunegala','Kuliyapitiya',TRUE),
  ('North Western','Kurunegala','Wariyapola',TRUE),
  ('North Western','Kurunegala','Nikaweratiya',TRUE),
  ('North Western','Kurunegala','Alawwa',TRUE),
  ('North Western','Kurunegala','Narammala',TRUE),
  ('North Western','Kurunegala','Mawathagama',TRUE),
  ('North Western','Kurunegala','Polgahawela',TRUE),
  -- North Western – Puttalam
  ('North Western','Puttalam','Puttalam',TRUE),
  ('North Western','Puttalam','Chilaw',TRUE),
  ('North Western','Puttalam','Dankotuwa',TRUE),
  ('North Western','Puttalam','Wennappuwa',TRUE),
  ('North Western','Puttalam','Marawila',TRUE),
  ('North Western','Puttalam','Nattandiya',TRUE),
  ('North Western','Puttalam','Kalpitiya',TRUE),
  -- North Central – Anuradhapura
  ('North Central','Anuradhapura','Anuradhapura',TRUE),
  ('North Central','Anuradhapura','Tambuttegama',TRUE),
  ('North Central','Anuradhapura','Medawachchiya',TRUE),
  ('North Central','Anuradhapura','Mihintale',TRUE),
  -- North Central – Polonnaruwa
  ('North Central','Polonnaruwa','Polonnaruwa',TRUE),
  ('North Central','Polonnaruwa','Habarana',TRUE),
  ('North Central','Polonnaruwa','Hingurakgoda',TRUE),
  -- Uva – Badulla
  ('Uva','Badulla','Badulla',TRUE),
  ('Uva','Badulla','Bandarawela',TRUE),
  ('Uva','Badulla','Haputale',TRUE),
  ('Uva','Badulla','Ella',TRUE),
  ('Uva','Badulla','Welimada',TRUE),
  ('Uva','Badulla','Mahiyanganaya',TRUE),
  -- Uva – Monaragala
  ('Uva','Monaragala','Monaragala',TRUE),
  ('Uva','Monaragala','Bibila',TRUE),
  ('Uva','Monaragala','Kataragama',TRUE),
  ('Uva','Monaragala','Wellawaya',TRUE),
  -- Sabaragamuwa – Ratnapura
  ('Sabaragamuwa','Ratnapura','Ratnapura',TRUE),
  ('Sabaragamuwa','Ratnapura','Embilipitiya',TRUE),
  ('Sabaragamuwa','Ratnapura','Pelmadulla',TRUE),
  ('Sabaragamuwa','Ratnapura','Balangoda',TRUE),
  ('Sabaragamuwa','Ratnapura','Eheliyagoda',TRUE),
  ('Sabaragamuwa','Ratnapura','Kahawatta',TRUE),
  ('Sabaragamuwa','Ratnapura','Kuruwita',TRUE),
  -- Sabaragamuwa – Kegalle
  ('Sabaragamuwa','Kegalle','Kegalle',TRUE),
  ('Sabaragamuwa','Kegalle','Mawanella',TRUE),
  ('Sabaragamuwa','Kegalle','Rambukkana',TRUE),
  ('Sabaragamuwa','Kegalle','Warakapola',TRUE),
  ('Sabaragamuwa','Kegalle','Ruwanwella',TRUE),
  ('Sabaragamuwa','Kegalle','Deraniyagala',TRUE),
  ('Sabaragamuwa','Kegalle','Aranayake',TRUE)
ON CONFLICT DO NOTHING;
