spring.cloud.aws.region.static=eu-north-1
spring.datasource.url=jdbc:postgresql://database-1.c9a8c0cma54a.eu-north-1.rds.amazonaws.com:5432/postgres?currentSchema=galaxy,public
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=9a4f2c8d3b7a1e5f8g2h6j9k0l3m6n5o8p1q4r7s0t3u6v9w2x5y8z1a4b7c0d3e
jwt.expiration=86400000

# Server port
server.port=8080